apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-deployment
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      imagePullSecrets:
        - name: test-private-registry
      containers:
        - name: test-app
          image: 10.254.101.100:5000/jenkins/test-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: application-config
              mountPath: "/usr/myapp"
              readOnly: true
      volumes:
        - name: application-config
          configMap:
            name: test-app-configmap
            items:
              - key: application.properties
                path: application.properties